/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OurClientsRouteImport } from './routes/our-clients'
import { Route as KnowledgeCentreRouteImport } from './routes/knowledge-centre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OurClientsRoute = OurClientsRouteImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCentreRoute = KnowledgeCentreRouteImport.update({
  id: '/knowledge-centre',
  path: '/knowledge-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/knowledge-centre': typeof KnowledgeCentreRoute
  '/our-clients': typeof OurClientsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/knowledge-centre': typeof KnowledgeCentreRoute
  '/our-clients': typeof OurClientsRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consulting': typeof ConsultingRoute
  '/contact': typeof ContactRoute
  '/knowledge-centre': typeof KnowledgeCentreRoute
  '/our-clients': typeof OurClientsRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consulting'
    | '/contact'
    | '/knowledge-centre'
    | '/our-clients'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consulting'
    | '/contact'
    | '/knowledge-centre'
    | '/our-clients'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consulting'
    | '/contact'
    | '/knowledge-centre'
    | '/our-clients'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultingRoute: typeof ConsultingRoute
  ContactRoute: typeof ContactRoute
  KnowledgeCentreRoute: typeof KnowledgeCentreRoute
  OurClientsRoute: typeof OurClientsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-clients': {
      id: '/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof OurClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-centre': {
      id: '/knowledge-centre'
      path: '/knowledge-centre'
      fullPath: '/knowledge-centre'
      preLoaderRoute: typeof KnowledgeCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultingRoute: ConsultingRoute,
  ContactRoute: ContactRoute,
  KnowledgeCentreRoute: KnowledgeCentreRoute,
  OurClientsRoute: OurClientsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
